### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by ug-kim** [ashawkey/cubvh#7]
Can you tell me what torch and CUDA version I have to install?

Installation failed with my environment (1.12.0+cu116 + python 3.9)

**Comment by ug-kim** [comment]
My error log is below.

```bash
Processing /home/ugkim/bucketplace/cubvh
  Preparing metadata (setup.py) ... done
Requirement already satisfied: ninja in /home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages (from cubvh==0.1.0) (1.11.1)
Requirement already satisfied: trimesh in /home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages (from cubvh==0.1.0) (3.21.5)
Requirement already satisfied: opencv-python in /home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages (from cubvh==0.1.0) (4.7.0.72)
Requirement already satisfied: torch in /home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages (from cubvh==0.1.0) (1.12.0+cu116)
Requirement already satisfied: numpy in /home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages (from cubvh==0.1.0) (1.22.4)
Requirement already satisfied: tqdm in /home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages (from cubvh==0.1.0) (4.65.0)
Requirement already satisfied: matplotlib in /home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages (from cubvh==0.1.0) (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages (from matplotlib->cubvh==0.1.0) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages (from matplotlib->cubvh==0.1.0) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages (from matplotlib->cubvh==0.1.0) (4.39.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages (from matplotlib->cubvh==0.1.0) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages (from matplotlib->cubvh==0.1.0) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages (from matplotlib->cubvh==0.1.0) (9.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages (from matplotlib->cubvh==0.1.0) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages (from matplotlib->cubvh==0.1.0) (2.8.2)
Requirement already satisfied: importlib-resources>=3.2.0 in /home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages (from matplotlib->cubvh==0.1.0) (5.12.0)
Requirement already satisfied: typing-extensions in /home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages (from torch->cubvh==0.1.0) (4.5.0)
Requirement already satisfied: zipp>=3.1.0 in /home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib->cubvh==0.1.0) (3.15.0)
Requirement already satisfied: six>=1.5 in /home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib->cubvh==0.1.0) (1.16.0)
Building wheels for collected packages: cubvh
  Building wheel for cubvh (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [110 lines of output]
      Found Eigen version 3.3.4 at /usr/include/eigen3
      Found eigen at /usr/include/eigen3
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/cubvh
      copying cubvh/__init__.py -> build/lib.linux-x86_64-cpython-39/cubvh
      copying cubvh/api.py -> build/lib.linux-x86_64-cpython-39/cubvh
      running build_ext
      /home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/utils/cpp_extension.py:820: UserWarning: There are no g++ version bounds defined for CUDA version 11.6
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building '_cubvh' extension
      creating /home/ugkim/bucketplace/cubvh/build/temp.linux-x86_64-cpython-39
      creating /home/ugkim/bucketplace/cubvh/build/temp.linux-x86_64-cpython-39/home
      creating /home/ugkim/bucketplace/cubvh/build/temp.linux-x86_64-cpython-39/home/ugkim
      creating /home/ugkim/bucketplace/cubvh/build/temp.linux-x86_64-cpython-39/home/ugkim/bucketplace
      creating /home/ugkim/bucketplace/cubvh/build/temp.linux-x86_64-cpython-39/home/ugkim/bucketplace/cubvh
      creating /home/ugkim/bucketplace/cubvh/build/temp.linux-x86_64-cpython-39/home/ugkim/bucketplace/cubvh/src
      Emitting ninja build file /home/ugkim/bucketplace/cubvh/build/temp.linux-x86_64-cpython-39/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/3] /usr/local/cuda-11.6/bin/nvcc  -I/home/ugkim/bucketplace/cubvh/include -I/usr/include/eigen3 -I/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/include -I/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/include/TH -I/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda-11.6/include -I/home/ugkim/miniconda3/envs/fusion/include/python3.9 -c -c /home/ugkim/bucketplace/cubvh/src/api.cu -o /home/ugkim/bucketplace/cubvh/build/temp.linux-x86_64-cpython-39/home/ugkim/bucketplace/cubvh/src/api.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++14 --expt-extended-lambda --expt-relaxed-constexpr -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=_cubvh -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
      FAILED: /home/ugkim/bucketplace/cubvh/build/temp.linux-x86_64-cpython-39/home/ugkim/bucketplace/cubvh/src/api.o
      /usr/local/cuda-11.6/bin/nvcc  -I/home/ugkim/bucketplace/cubvh/include -I/usr/include/eigen3 -I/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/include -I/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/include/TH -I/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda-11.6/include -I/home/ugkim/miniconda3/envs/fusion/include/python3.9 -c -c /home/ugkim/bucketplace/cubvh/src/api.cu -o /home/ugkim/bucketplace/cubvh/build/temp.linux-x86_64-cpython-39/home/ugkim/bucketplace/cubvh/src/api.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++14 --expt-extended-lambda --expt-relaxed-constexpr -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=_cubvh -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
      /home/ugkim/bucketplace/cubvh/src/api.cu:1:9: warning: #pragma once in main file
       #pragma once
               ^~~~
      In file included from /usr/include/eigen3/Eigen/Dense:1:0,
                       from /home/ugkim/bucketplace/cubvh/include/cubvh/api.h:3,
                       from /home/ugkim/bucketplace/cubvh/src/api.cu:3:
      /usr/include/eigen3/Eigen/Core:42:14: fatal error: math_functions.hpp: No such file or directory
           #include <math_functions.hpp>
                    ^~~~~~~~~~~~~~~~~~~~
      compilation terminated.
      [2/3] /usr/local/cuda-11.6/bin/nvcc  -I/home/ugkim/bucketplace/cubvh/include -I/usr/include/eigen3 -I/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/include -I/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/include/TH -I/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda-11.6/include -I/home/ugkim/miniconda3/envs/fusion/include/python3.9 -c -c /home/ugkim/bucketplace/cubvh/src/bvh.cu -o /home/ugkim/bucketplace/cubvh/build/temp.linux-x86_64-cpython-39/home/ugkim/bucketplace/cubvh/src/bvh.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++14 --expt-extended-lambda --expt-relaxed-constexpr -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=_cubvh -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
      FAILED: /home/ugkim/bucketplace/cubvh/build/temp.linux-x86_64-cpython-39/home/ugkim/bucketplace/cubvh/src/bvh.o
      /usr/local/cuda-11.6/bin/nvcc  -I/home/ugkim/bucketplace/cubvh/include -I/usr/include/eigen3 -I/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/include -I/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/include/TH -I/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda-11.6/include -I/home/ugkim/miniconda3/envs/fusion/include/python3.9 -c -c /home/ugkim/bucketplace/cubvh/src/bvh.cu -o /home/ugkim/bucketplace/cubvh/build/temp.linux-x86_64-cpython-39/home/ugkim/bucketplace/cubvh/src/bvh.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++14 --expt-extended-lambda --expt-relaxed-constexpr -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=_cubvh -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
      In file included from /usr/include/eigen3/Eigen/Dense:1:0,
                       from /home/ugkim/bucketplace/cubvh/include/cubvh/common.h:14,
                       from /home/ugkim/bucketplace/cubvh/src/bvh.cu:2:
      /usr/include/eigen3/Eigen/Core:42:14: fatal error: math_functions.hpp: No such file or directory
           #include <math_functions.hpp>
                    ^~~~~~~~~~~~~~~~~~~~
      compilation terminated.
      [3/3] c++ -MMD -MF /home/ugkim/bucketplace/cubvh/build/temp.linux-x86_64-cpython-39/home/ugkim/bucketplace/cubvh/src/bindings.o.d -pthread -B /home/ugkim/miniconda3/envs/fusion/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/ugkim/miniconda3/envs/fusion/include -I/home/ugkim/miniconda3/envs/fusion/include -fPIC -O2 -isystem /home/ugkim/miniconda3/envs/fusion/include -fPIC -I/home/ugkim/bucketplace/cubvh/include -I/usr/include/eigen3 -I/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/include -I/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/include/TH -I/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda-11.6/include -I/home/ugkim/miniconda3/envs/fusion/include/python3.9 -c -c /home/ugkim/bucketplace/cubvh/src/bindings.cpp -o /home/ugkim/bucketplace/cubvh/build/temp.linux-x86_64-cpython-39/home/ugkim/bucketplace/cubvh/src/bindings.o -O3 -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=_cubvh -D_GLIBCXX_USE_CXX11_ABI=0
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build
          subprocess.run(
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/ugkim/bucketplace/cubvh/setup.py", line 118, in <module>
          setup(
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 586, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1487, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/ugkim/miniconda3/envs/fusion/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cubvh
  Running setup.py clean for cubvh
Failed to build cubvh
ERROR: Could not build wheels for cubvh, which is required to install pyproject.toml-based projects
```

**Comment by ashawkey** [comment]
@ug-kim Hi, this is strange as `fatal error: math_functions.hpp: No such file or directory` seems to be a error caused by low CUDA version (https://stackoverflow.com/questions/43113508/math-functions-hpp-not-found-when-using-cuda-with-eigen). Could you check your cuda and eigen versions?

**Comment by ug-kim** [comment]
Hi, thank you for your reply.
What cuda and eigen versions do I have to install?

**Comment by arturodrt** [comment]
I am getting a similar error while trying to install, I am using CUDA 11.7:

      RuntimeError: Error compiling objects for extension
      [end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> cubvh

**Comment by DiamondGlassDrill** [comment]
Do get the same error in CUDA 11.8, could someone help? As I need it urgently for a project. Thanks in advance.

**Comment by DiamondGlassDrill** [comment]
Working on it but came from one error to another:
o currently getting the error:
...\mambaforge\envs\magic123\lib\site-packages\torch\include\pybind11/eigen.h(35): fatal error C1083: File cannot be opened: "Eigen/Core": No such file or directory
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
File "...\mambaforge\envs\magic123\lib\site-packages\torch\utils\cpp_extension.py", line 1893, in _run_ninja_build
subprocess.run(
File "...\mambaforge\envs\magic123\lib\subprocess.py", line 526, in run
raise CalledProcessError(retcode, process.args,

Going down the rabbid hole I am currently in the pybind11/eigen.h and there it tries to load Eigen but no folder is in the pybind11
From eigen.h (extracted)

```
/*
    pybind11/eigen.h: Transparent conversion for dense and sparse Eigen matrices

    Copyright (c) 2016 Wenzel Jakob <wenzel.jakob@epfl.ch>

    All rights reserved. Use of this source code is governed by a
    BSD-style license that can be found in the LICENSE file.
*/

#pragma once

/* HINT: To suppress warnings originating from the Eigen headers, use -isystem.
   See also:
       https://stackoverflow.com/questions/2579576/i-dir-vs-isystem-dir
       https://stackoverflow.com/questions/1741816/isystem-for-ms-visual-studio-c-compiler
*/

#include "numpy.h"

// The C4127 suppression was introduced for Eigen 3.4.0. In theory we could
// make it version specific, or even remove it later, but considering that
// 1. C4127 is generally far more distracting than useful for modern template code, and
// 2. we definitely want to ignore any MSVC warnings originating from Eigen code,
//    it is probably best to keep this around indefinitely.
#if defined(_MSC_VER)
#    pragma warning(push)
#    pragma warning(disable : 4127) // C4127: conditional expression is constant
#    pragma warning(disable : 5054) // https://github.com/pybind/pybind11/pull/3741
//       C5054: operator '&': deprecated between enumerations of different types
#elif defined(__MINGW32__)
#    pragma GCC diagnostic push
#    pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
#endif

#include <Eigen/Core>
#include <Eigen/SparseCore>
```

Maybe someone has the same issue and could help?

I have pytorch 2.0.1 installed for python 3.10 and CUDA 11.8 with cuDNN 8.0

**Things done so far:**

pip install eigen (0.0.1 from 2022) didn't help (uninstalled)
mamba install eigenpy (3.1.0 from July 2023) (gives latest Eigen 3.4.0 (2021)) but didn't help

**Comment by DiamondGlassDrill** [comment]
Solved one issue, as I added within the setup.py of cubvh the missing link to the right Eigen folder.
```

    # Get the current path of the active conda/mamba environment
    current_env_path = os.environ.get('CONDA_PREFIX', None)
    if current_env_path:
        eigen_path = os.path.join(current_env_path, 'Library', 'include', 'eigen3')
        print(eigen_path)
    else:
        eigen_path = None
    if eigen_path:
        try_paths.append(eigen_path)
```
**A bit dirty but it works for now.

Another issue appeared.**
```

    ...\Library\include\eigen3\Eigen\src/Core/Ref.h(63): note: See declaration of  "Eigen::RefBase<Eigen::Ref<const Eigen::Matrix<unsigned int,-1,3,1,-1,3>,0,Eigen::OuterStride<-1>>>::StrideType"

      ...\mambaforge\envs\magic123\Library\include\eigen3\Eigen\src/Core/Ref.h(329): note: See declaration of "Eigen::RefBase<Eigen::Ref<const Eigen::Matrix<unsigned int,-1,3,1,-1,3>,0,Eigen::OuterStride<-1>>>"

      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "...\lib\site-packages\torch\utils\cpp_extension.py", line 1893, in _run_ninja_build
          subprocess.run(
        File "...\lib\subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
```
I know it is not hinting to the error but currently have lost already 2h; will debug it later, but maybe someone else has the same issue and will fix it meanwhile :)

**Comment by XuYunqiu** [comment]
Does anyone resolve this issue?
I get the same installation error. I'm using `torch 2.0.1` + `CUDA 11.8` + `Eigen 3.3.4`.

**Comment by XuYunqiu** [comment]
> Does anyone resolve this issue? I get the same installation error. I'm using `torch 2.0.1` + `CUDA 11.8` + `Eigen 3.3.4`.

After upgrading the Eigen to 3.3.7 as suggested, my issue seems to be solved.
https://github.com/ashawkey/cubvh/blob/d3e923c90e56974d39f57c2e2b9bf372d2e45870/setup.py#L21

**Comment by ZuoXuhui** [comment]
> > Does anyone resolve this issue? I get the same installation error. I'm using `torch 2.0.1` + `CUDA 11.8` + `Eigen 3.3.4`.
> 
> After upgrading the Eigen to 3.3.7 as suggested, my issue seems to be solved.
> 
> https://github.com/ashawkey/cubvh/blob/d3e923c90e56974d39f57c2e2b9bf372d2e45870/setup.py#L21

I did the same thing and successfully solved the problem too. I'm using torch 1.12.1 + CUDA 11.3 + Eigen 3.3.7.

**Comment by ashawkey** [comment]
this should have been fixed.
