### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by Taxalfer** [ashawkey/cubvh#9]
I just run the command "pip install git+https://github/ashawkey/cubvh" and got problem below:

===============================
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-fc2yzsks/setup.py", line 3, in <module>
          from torch.utils.cpp_extension import BuildExtension, CUDAExtension
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
================================
how can i fix this.

**Comment by Taxalfer** [comment]
I am sorry for asking such a stupid question. After installed torch, you can fix this problem.
